'use strict';

module.exports = Object.freeze({
   
    APPOINMENT_EXIST_CODE: "Appoiment code must be unique!",
    APPOINMENT_CREATE_SUCCESS: "Create appoiment success!",
    APPOINMENT_CREATE_FAIL: "Create appoiment fail!",
    APPOINMENT_UPDATE_SUCCESS: "Update appoiment success!",
    APPOINMENT_UPDATE_FAIL: "Update appoiment fail!",
    APPOINMENT_PARAM_REQUIRED: "The param must be required!",

    APPOINMENT_COMEBACK_JOB_REQUIRED: "APPOINMENT_COMEBACK_JOB_REQUIRED",
    APPOINMENT_PAYMENT_TYPE_REQUIRED: "APPOINMENT_PAYMENT_TYPE_REQUIRED",
    APPOINMENT_JOB_SOURCE_REQUIRED: "APPOINMENT_JOB_SOURCE_REQUIRED",
    APPOINMENT_PART_SOURCE_REQUIRED: "APPOINMENT_PART_SOURCE_REQUIRED",
    APPOINMENT_UPDATE_SUCCESS : "APPOINMENT_UPDATE_SUCCESS",
});